const feedbackTopics = [
  'Application Usability',
  'Performance Issues',
  'Feature Requests',
  'Bug Reports',
  'User Interface Design',
  'Content Accuracy',
  'Accessibility',
  'Customer Support',
  'Privacy Concerns',
  'Overall Experience',
  'Installation Process',
  'Update Process',
  'Compatibility Issues',
  'Security Issues',
  'User Training',
  'Documentation Quality',
  'Localization and Language Support',
  'Integration with Other Tools',
  'Data Export/Import',
  'Customizability',
  'Error Messages',
  'Mobile Experience',
  'Desktop Experience',
  'Speed and Responsiveness',
  'Third-Party Integrations',
  'Feature Discoverability',
  'Onboarding Experience',
  'Search Functionality',
  'Notifications and Alerts',
  'Feedback Mechanisms'
];

export default feedbackTopics;
