const foodItems = [
  'Barley Whole grain flour',
  'Corn Whole grain flour',
  'Corn Flakes',
  'Corn Bread',
  'Millet Pearl Whole grain flour',
  'Oat Whole grain flour',
  'Rye Whole grain flour',
  'Rice Polished',
  'Rice Polished Boiled',
  'Rice Polished Fried',
  'Rice Flakes',
  'Sorghum whole grain flour',
  'Sorghum Bread',
  'Vermicelli',
  'Wheat Whole grain flour',
  'Wheat flour refined',
  'Wheat flour granular',
  'Wheat Bread Nan',
  'Wheat Bread Chapati',
  'Wheat Bread Paratha',
  'Wheat Bread Puri',
  'Wheat Bread Double Roti',
  'Wheat Flour Biscuit',
  'Broad Bean Raw Lobia',
  'Broad Bean Raw Lobia Cooked',
  'Chickpea Channa',
  'Chickpea Channa Cooked',
  'Cow Pea Raw Rawan',
  'Cow Pea Raw Rawan Cooked',
  'Kidney Bean Raw',
  'Kidney Bean Raw Cooked',
  'Lentil Raw',
  'Lentil Cooked',
  'Mung Bean Raw',
  'Mung Bean Cooked',
  'Mash Bean Raw',
  'Mash Bean Cooked',
  'Pigeon Pea Raw Arhar',
  'Pigeon Pea Cooked Arhar',
  'Pea Garden Raw Mattar',
  'Pea Garden Cooked Mattar',
  'SoyBean Seed',
  'Sunflower Seed',
  'Bath Sponge Tori',
  'Bottle Gourd Kaddu',
  'Bitter Gourd Karela',
  'Brinjal Baingan',
  'Cauliflower Phool Gobi',
  'Cucumber Khira',
  'Cabbage',
  'Kulfa Sag kulfa',
  'Lady finger Bhindi',
  'Lettuce',
  'Mountain ebony Kutchnar',
  'Mustard Leaves Sarson Sag',
  'Moongra',
  'Mint Leaves Podina',
  'Mushroom Khumbi',
  'Pepper Sweet Mirch',
  'Pepper Hot Surkh Mirch',
  'Pumpkin Halva Kadu',
  'Spinach Palak',
  'Tomato',
  'Tinda',
  'Beet Root',
  'Carrots',
  'Colocasia Arvi',
  'Potato',
  'Radish',
  'Turnip',
  'Apple',
  'Apricot',
  'Banana Ripe',
  'Black Berry',
  'Dates Dried',
  'Dates Fresh',
  'Fig Fresh',
  'Grapes',
  'Guava Whole',
  'Jaman',
  'Lemon',
  'Lichi',
  'Lime',
  'Lime Sweet',
  'Loquat',
  'Mango',
  'Melon Musk',
  'Melon Water',
  'Mulbery Black Shehtut',
  'Mandarin Kinno',
  'Mandarin Narangi',
  'Orange Sweet Malta',
  'Peach',
  'Pear',
  'Persimmon Amlok',
  'Pineapple',
  'Plum',
  'Pomegranate',
  'Papaya Ripe',
  'Phalsa',
  'Strawberry',
  'Zizyphus Desi Ber',
  'Zizyphus Sova Ber',
  'Almond',
  'Anise',
  'Walnut',
  'Peanut Roasted',
  'Cashew Nut',
  'Coconut',
  'Chilghoza roasted',
  'Pistachio',
  'Poppy Seed',
  'Peanut',
  'Sesame Seed',
  'Raisin',
  'Buttermilk Lassi',
  'Curd Dahi',
  'Cheese',
  'Cream Balai',
  'Milk Buffalo Fluid Whole',
  'Milk Cow Fluid Whole',
  'Milk Goat Fluid Whole',
  'Milk Cow Dried Skimmed',
  'Milk Cow Dried Whole',
  'Yogurt',
  'Ice Cream',
  'Beef',
  'Beef Liver',
  'Beef Kidney',
  'Beef Heart',
  'Buffalo Meat',
  'Chicken Meat',
  'Duck Meat',
  'Goat Meat',
  'Goat Liver',
  'Goat Kidney',
  'Goat Heart',
  'Sheep Meat',
  'Pigeon Meat',
  'Crab',
  'Fish Roa',
  'Fish Promfret',
  'Fish Khaga',
  'Fish Shanghara',
  'Fish Soal',
  'Fish Surmai',
  'Lobster',
  'Prawn',
  'Shrimp',
  'Chicken Egg White Raw',
  'Chicken Egg Yolk Raw',
  'Chicken Egg Whole Raw',
  'Chicken Egg Boiled',
  'Duck Egg White Raw',
  'Duck Egg Yolk Raw',
  'Duck Egg Whole Raw',
  'Duck Egg Boiled',
  'Sugar White',
  'Sugar Brown',
  'Gur',
  'Honey',
  'Barfi',
  'Jalebi',
  'Khoa Whole Buffalo Milk',
  'Halwa Sohen',
  'Carbonated: Pepsi, Coke, 7Up',
  'Lemon Juice',
  'Mango Juice',
  'Coffee Instant Dry Powder',
  'Black Tea Leaves Dried',
  'Green Tea Leaves Dried',
  'Kitchri',
  'Rice Kheer',
  'Feerni',
  'Wheat Dalia',
  'Banana Kheer',
  'Chapati',
  'Daal Masur Curry',
  'Kidney Bean Curry Kalool',
  'Alu Gosht',
  'Kofta',
  'Pulao Gosht',
  'Chapal Kabab',
  'Shami Kabab',
  'Chicken Curry',
  'Haleem',
  'Sajji',
  'Machli Fried Fish',
  'Biryani',
  'Halwa Suji',
  'Rice Pudding Kheer',
  'Zarda',
  'Halwa Gajjar'
];

export default foodItems;
